Model:
    name: "InSPyReNet_SwinB"
    depth: 64
    pretrained: True
    base_size: [384, 384]
    threshold: 512

Train:
    Dataset:
        type: "RGB_Dataset"
        root: "data/Train_Dataset"
        sets: ['DUTS-TR', 'HRSOD-TR']
        transforms:
            static_resize: 
                size: [384, 384]
            random_scale_crop:
                range: [0.75, 1.25]
            random_flip:
                lr: True
                ud: False
            random_rotate:
                range: [-10, 10]
            random_image_enhance:
                methods: ['contrast', 'sharpness', 'brightness']
            tonumpy: NULL
            normalize: 
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
            totensor: NULL
    Dataloader:
        batch_size: 6
        shuffle: True
        num_workers: 8
        pin_memory: False
    Optimizer:
        type: "Adam"
        lr: 1.0e-05
        weight_decay: 0.0
        mixed_precision: False
    Scheduler:
        type: "PolyLr"
        epoch: 60
        gamma: 0.9
        minimum_lr: 1.0e-07
        warmup_iteration: 12000
    Checkpoint:
        checkpoint_epoch: 1
        checkpoint_dir: "snapshots/InSPyReNet_SwinB_DH_LR"
    Debug:
        keys: ['saliency', 'laplacian']
    
Test:
    Dataset:
        type: "RGB_Dataset"
        root: "data/Test_Dataset"
        sets:  ['DUTS-TE', 'DUT-OMRON', 'ECSSD', 'HKU-IS', 'PASCAL-S', 'DAVIS-S', 'HRSOD-TE', 'UHRSD-TE']
        transforms:
            dynamic_resize:
                L: 1280
            tonumpy: NULL
            normalize: 
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
            totensor: NULL
    Dataloader:
        num_workers: 8
        pin_memory: True
    Checkpoint:
        checkpoint_dir: "snapshots/InSPyReNet_SwinB_DH_LR"

Eval:
    gt_root: "data/Test_Dataset"
    pred_root: "snapshots/InSPyReNet_SwinB_DH_LR"
    result_path: "results"
    datasets: ['DUTS-TE', 'DUT-OMRON', 'ECSSD', 'HKU-IS', 'PASCAL-S', 'DAVIS-S', 'HRSOD-TE', 'UHRSD-TE']
    metrics: ['Sm', 'mae', 'adpEm', 'maxEm', 'avgEm', 'adpFm', 'maxFm', 'avgFm', 'wFm', 'mBA']
