Model:
    name: "EGNet_ResNet"
    depth: None
    pretrained: True

Test:
    Dataset:
        type: "RGB_Dataset"
        root: "data/RGB_Dataset/Test_Dataset"
        sets: ['DUTS-TE', 'DUT-OMRON', 'ECSSD', 'HKU-IS', 'PASCAL-S', 'HRSOD']
        transforms:
            resize:
                size: [384, 384]
            tonumpy: NULL
            normalize: 
                mean: [104.00699, 116.66877, 122.67892]
                div: 1
            totensor: NULL
    Dataloader:
        num_workers: 8
        pin_memory: True
    Checkpoint:
        checkpoint_dir: "snapshots/SotA/EGNet"

Eval:
    gt_root: "data/RGB_Dataset/Test_Dataset"
    pred_root: "snapshots/SotA/EGNet"
    result_path: "results"
    datasets: ['DUTS-TE', 'DUT-OMRON', 'ECSSD', 'HKU-IS', 'PASCAL-S', 'HRSOD']
    metrics: ['Sm', 'mae', 'adpEm', 'maxEm', 'avgEm', 'adpFm', 'maxFm', 'avgFm', 'wFm']