Model:
    name: "F3Net_SwinB"
    depth: None
    pretrained: True
    


Test:
    Dataset:
        type: "RGB_Dataset"
        root: "data/RGB_Dataset/Test_Dataset"
        sets: ['DUTS-TE', 'DUT-OMRON', 'ECSSD', 'HKU-IS', 'PASCAL-S', 'HRSOD', 'UHRSD-TE']
        transforms:
            resize:
                size: [384, 384]
            tonumpy: NULL
            normalize: 
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
            totensor: NULL
    Dataloader:
        num_workers: 8
        pin_memory: True
    Checkpoint:
        checkpoint_dir: "snapshots/SotA/F3Net_SwinB"

Eval:
    gt_root: "data/RGB_Dataset/Test_Dataset"
    pred_root: "snapshots/SotA/F3Net_SwinB"
    result_path: "results"
    datasets: ['DUTS-TE', 'DUT-OMRON', 'ECSSD', 'HKU-IS', 'PASCAL-S', 'HRSOD', 'UHRSD-TE']
    metrics: ['Sm', 'mae', 'adpEm', 'maxEm', 'avgEm', 'adpFm', 'maxFm', 'avgFm', 'wFm', 'mBA']