Model:
    name: "F3Net"
    depth: None
    pretrained: True
    


Test:
    Dataset:
        type: "RGB_Dataset"
        root: "data/RGB_Dataset/Test_Dataset"
        sets: ['HRSOD'] #['DUTS-TE', 'DUT-OMRON', 'ECSSD', 'HKU-IS', 'PASCAL-S']
        transforms:
            resize:
                size: [384, 384]
            tonumpy: NULL
            normalize: 
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
            totensor: NULL
        transforms_PM:
            dynamic_resize:
                patch_size: 384
                stride: 192
            tonumpy: NULL
            normalize: 
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
            totensor: NULL
    Dataloader:
        num_workers: 8
        pin_memory: True
    Checkpoint:
        checkpoint_dir: "snapshots/SotA/F3Net"

Eval:
    gt_root: "data/RGB_Dataset/Test_Dataset"
    pred_root: "snapshots/SotA/F3Net"
    result_path: "results"
    datasets: ['HRSOD'] # ['DUTS-TE', 'DUT-OMRON', 'ECSSD', 'HKU-IS', 'PASCAL-S']
    metrics: ['Sm', 'mae', 'adpEm', 'maxEm', 'avgEm', 'adpFm', 'maxFm', 'avgFm', 'wFm']