Model:
    name: "InSPyReNetV2_SwinB"
    depth: 64
    pretrained: True
    base_size: 384
    
PM:
    patch_size: 384
    stride: 96

Train:
    Dataset:
        type: "RGBD_Dataset"
        root: "data/RGBD_Dataset/Train_Dataset"
        sets: ['NJU2K+NLPR']
        transforms:
            resize: 
                size: [384, 384]
            random_scale_crop:
                range: [0.75, 1.25]
            random_flip:
                lr: True
                ud: False
            random_rotate:
                range: [-10, 10]
            random_image_enhance:
                methods: ['contrast', 'sharpness', 'brightness']
            tonumpy: NULL
            normalize: 
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
            totensor: NULL
    Dataloader:
        batch_size: 6
        shuffle: True
        num_workers: 8
        pin_memory: False
    Optimizer:
        type: "Adam"
        lr: 1.0e-05
        weight_decay: 0.0
        mixed_precision: False
    Scheduler:
        type: "PolyLr"
        epoch: 300
        gamma: 0.9
        minimum_lr: 1.0e-07
        warmup_iteration: 12000
    Checkpoint:
        checkpoint_epoch: 1
        checkpoint_dir: "snapshots/InSPyReNetV2_SwinB"
    Debug:
        keys: ['gaussian', 'laplacian']
    HyperTune:
        HyperParameter: ['Train', 'Optimizer', 'lr']
        Range: [1.0e-6, 2.4e-5, 24]
    
Test:
    Dataset:
        type: "RGBD_Dataset"
        root: "data/RGBD_Dataset/Test_Dataset"
        sets: ['DES', 'LFSD', 'NJU2K', 'NLPR', 'SIP', 'STERE']
        transforms:
            resize:
                size: [384, 384]
            tonumpy: NULL
            normalize: 
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
            totensor: NULL
        transforms_PM:
            dynamic_resize:
                base_size: 384
                stride: 192
            tonumpy: NULL
            normalize: 
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
            totensor: NULL
    Dataloader:
        num_workers: 8
        pin_memory: True
    Checkpoint:
        checkpoint_dir: "snapshots/InSPyReNetV2_SwinB"

Eval:
    gt_root: "data/RGBD_Dataset/Test_Dataset"
    pred_root: "snapshots/InSPyReNetV2_SwinB"
    result_path: "results"
    datasets: ['DES', 'LFSD', 'NJU2K', 'NLPR', 'SIP', 'STERE']
    metrics: ['Sm', 'mae', 'adpEm', 'maxEm', 'avgEm', 'adpFm', 'maxFm', 'avgFm', 'wFm']
